### ISSUE TITLE
Timeout values change unexpectedly

### ISSUE THREAD

**Issue by per1234** [kdschlosser/TCP-Events#2]
Timeout values change every time the Send an Event dialog is opened.
Try this:
- Add Send an Event action - set the timeout values to 1.00 and 2.00
![1](https://cloud.githubusercontent.com/assets/8572152/9432890/18b7659c-49df-11e5-8f05-d2a2d99260f7.gif)
- Click OK
- Double click on the Send and Event action - the timeout values are now 2.00 and 0.00
![2](https://cloud.githubusercontent.com/assets/8572152/9432896/39c945fc-49df-11e5-969f-4430549b8bb3.gif)
- Click OK
- Double click on the Send and Event action - the timeout values are now 0.00 and 0.00
![3](https://cloud.githubusercontent.com/assets/8572152/9432903/5c7a9790-49df-11e5-8e5d-df66931e461a.gif)

This seems to be caused by having the evtPayload parameter before the timeout parameters which is why I had them in that order. But with the evtPayload parameter after the timeout parameters it breaks backwards compatibility. I'm not sure if there is a workaround for this. The only solution I have come up with is to configure the timeouts in the plugin configuration dialog. This is better in a way because then the timeout values only have to be set once the downside is it could potentially be nice to have different timeout values for different event destinations. Considering the timeout has never been accessible for configuration at all I think it's not so bad to do it in the plugin config.

**Comment by kdschlosser** [comment]
that has to do with the tab order i told ya about. i have to get the alignment. it's actually swapping fields not changing them randomly.

**Comment by per1234** [comment]
I'm thinking it might be best to set the default timeout values in the TCPEvents plugin configuration(as I have my version set up currently) and then allow action specific timeout values to be set using python commands but not having the timeout fields in the action configuration dialogs. This would make it more simple for the average user but still allow the flexibility of setting the timeout value for the action if needed.
